version: '3.4'

services:

  sourcingdb:
    container_name: sourcingdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db

    ports:
      - "27017:27017"



  mt.e-sourcing.products:
    container_name: mtproduct
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
    depends_on:
       - sourcingdb
    volumes:
       - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
       - ${HOME}/ASP.NET/Https:/root/.aspnet/https/
       
    ports:
      - "8001:80"

   
  mt.e-sourcing.sourcing.api:
    container_name: mtsourcingsourcingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
    depends_on:
      - sourcingdb
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https/
    ports:
      - "8002:80"

